version: '3.8'
services:
  omnisentinel-backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.example
    ports:
      - '8000:8000'
  discord-bot:
    build: ./discord-bot
    volumes:
      - ./discord-bot:/app
    env_file:
      - ./discord-bot/.env.example
    depends_on:
      - omnisentinel-backend
